[env:xiao_nrf52840_plus]
platform = https://github.com/Seeed-Studio/platform-seeedboards/archive/refs/heads/main.zip
board = seeed-xiao-afruitnrf52-nrf52840-plus
framework = arduino
monitor_speed = 115200
build_src_filter = +<xiao_main.cpp>
